# Site settings
title: Blog of a Fox
email: fox@vbfox.net
description: > # this means to ignore newlines until "baseurl:"
  Blog of Julien Roncaglia (aka VirtualBlackFox)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.vbfox.net" # the base hostname & protocol for your site
twitter_username: virtualblackfox
github_username:  vbfox

# Build settings
markdown: redcarpet
highlighter: pygments
exclude:
  - Gemfile*
  - readme.md
  - '*.cmd'
  - paket.*
  - '*.fsx'
  - '.fake'
  - 'packages'
  - 'appveyor.yml'