# Site settings
title: Blog of a Fox
email: fox@vbfox.net
description: > # this means to ignore newlines until "baseurl:"
  My name is Julien Roncaglia and this is my blog. Mainly about code
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.vbfox.net" # the base hostname & protocol for your site
twitter_username: virtualblackfox
github_username:  vbfox

# Build settings
markdown: redcarpet
