version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
environment:
  password:
    secure: SHp3N2vcWjhD8xFFopC4ufWnsSbyDowKSa+gCLRrIFA=
cache:
  - "%LocalAppData%\\NuGet\\Cache -> paket.lock"
  - "C:\\Ruby22-x64\\lib\\ruby\\gems\\2.2.0\\cache -> Gemfile.lock"
install:
- cmd: set PATH=C:\Ruby22-x64\bin;C:\Python27-x64;%PATH%
build_script:
- cmd: >-
    build.cmd CI
artifacts:
- path: _site
  name: Site